#!/usr/bin/python3

import math

def is_prime(n):
    if n < 2:
        return False
    if n == 2:
        return True
    if n % 2 == 0:
        return False
    for i in range(3, int(math.sqrt(n)) + 1, 2):
        if n % i == 0:
            return False
    return True

def factorize(n):
    for i in range(2, n):
        if n % i == 0 and is_prime(i):
            return i, n // i

def main(input_file):
    with open(input_file, 'r') as file:
        n = int(file.read())
        p, q = factorize(n)
        print("{}={}*{}".format(n, p, q))

if __name__ == "__main__":
    import sys
    if len(sys.argv) != 2:
        print("Usage: rsa <file>")
        sys.exit(1)
    main(sys.argv[1])
